export const categories = [
	{ name: "Fiction" },
	{ name: "Non-Fiction" },
	{ name: "Science Fiction" },
	{ name: "Fantasy" },
	{ name: "Mystery" },
	{ name: "Romance" },
	{ name: "Classics" },
	{ name: "Drama" },
	{ name: "Poetry" },
	{ name: "Biography" },
	{ name: "Historical Fiction" },
	{ name: "Children & Young Adult" },
] as const;

export const conditions = [
	{ exterior: "Like New", interior: "Clean", grade: "A+" },
	{ exterior: "Very Good", interior: "Minimal wear", grade: "A" },
	{ exterior: "Good", interior: "Light notes", grade: "B" },
	{ exterior: "Fair", interior: "Visible wear", grade: "C" },
] as const;

export const authors = [
	{
		name: "Mary Shelley",
		description:
			"English novelist best known for Frankenstein, a foundational work of Gothic fiction and early science fiction.",
	},
	{
		name: "Saint Augustine",
		description:
			"Theologian and philosopher of late antiquity whose writings shaped Western Christianity and philosophy.",
	},
	{
		name: "Emily Brontë",
		description: "English novelist and poet best known for Wuthering Heights.",
	},
	{
		name: "Herman Melville",
		description:
			"American novelist, short story writer, and poet best known for Moby-Dick.",
	},
	{
		name: "Jane Austen",
		description:
			"English novelist celebrated for sharp social observation and enduring romantic fiction.",
	},
	{
		name: "William Shakespeare",
		description:
			"English playwright and poet whose works remain central to world literature and theatre.",
	},
	{
		name: "E. M. Forster",
		description:
			"English novelist, essayist, and short story writer known for works exploring class, convention, and human connection.",
	},
	{
		name: "Lewis Carroll",
		description:
			"English author, mathematician, and logician best known for Alice's Adventures in Wonderland.",
	},
	{
		name: "Robert Louis Stevenson",
		description:
			"Scottish novelist and essayist known for adventure fiction and Gothic classics.",
	},
	{
		name: "George Eliot",
		description:
			"Pen name of Mary Ann Evans, an English novelist known for psychological realism and moral complexity.",
	},
	{
		name: "F. Scott Fitzgerald",
		description:
			"American novelist associated with the Jazz Age, best known for The Great Gatsby.",
	},
	{
		name: "Charlotte Brontë",
		description: "English novelist and poet best known for Jane Eyre.",
	},
	{
		name: "L. M. Montgomery",
		description:
			"Canadian author best known for emotionally rich novels including Anne of Green Gables and The Blue Castle.",
	},
	{
		name: "Fyodor Dostoevsky",
		description:
			"Russian novelist known for psychologically intense fiction exploring morality, guilt, and redemption.",
	},
	{
		name: "Louisa May Alcott",
		description:
			"American novelist best known for Little Women and other coming-of-age classics.",
	},
	{
		name: "Elizabeth von Arnim",
		description:
			"British novelist known for witty, emotionally perceptive fiction, including The Enchanted April.",
	},
	{
		name: "Oscar Wilde",
		description:
			"Irish writer and playwright celebrated for wit, satire, and works such as The Picture of Dorian Gray.",
	},
	{
		name: "Alexandre Dumas",
		description:
			"French novelist known for historical adventure fiction, including The Three Musketeers and its sequels.",
	},
	{
		name: "Bram Stoker",
		description: "Irish author best known for the Gothic horror novel Dracula.",
	},
	{
		name: "Mark Twain",
		description:
			"American writer and humorist best known for Adventures of Huckleberry Finn and Tom Sawyer.",
	},
	{
		name: "Jonathan Swift",
		description:
			"Anglo-Irish satirist and essayist best known for Gulliver's Travels and A Modest Proposal.",
	},
	{
		name: "Henrik Ibsen",
		description:
			"Norwegian playwright often called the father of modern drama.",
	},
	{
		name: "J. Lesslie Hall",
		description:
			"American scholar and translator known for an English translation of Beowulf.",
	},
] as const;

export const publishers = [
	{
		name: "Penguin Classics",
		description:
			"Curated seed publisher for classic literature editions in the webshop.",
	},
	{
		name: "Oxford World's Classics",
		description:
			"Curated seed publisher for annotated and academic classic editions.",
	},
	{
		name: "Vintage Classics",
		description:
			"Curated seed publisher for modern classic literature editions.",
	},
	{
		name: "Wordsworth Editions",
		description: "Curated seed publisher for affordable classic reprints.",
	},
	{
		name: "Everyman's Library",
		description: "Curated seed publisher for collectible hardcover classics.",
	},
] as const;

export const products = [
	{
		title: "Frankenstein; or, the Modern Prometheus",
		description:
			"Victor Frankenstein creates life through an unorthodox scientific experiment, only to recoil from the being he has made. A landmark Gothic novel blending horror, ambition, and moral tragedy.",
		price: 1399,
		discountPercentage: 10,
		weight: 320,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: ["https://www.gutenberg.org/cache/epub/84/pg84.cover.medium.jpg"],
		thumbnail: "https://www.gutenberg.org/cache/epub/84/pg84.cover.medium.jpg",
		tags: ["gothic", "classic", "science fiction", "horror"],
		era: "19th Century",
		genre: "Gothic Science Fiction",
		format: "Paperback",
		year: new Date("1818-01-01"),
		binding: "Softcover",
		categoryName: "Science Fiction",
		conditionGrade: "A",
		authorName: "Mary Shelley",
		publisherName: "Penguin Classics",
	},
	{
		title: "The City of God, Volume I",
		description:
			"A foundational work of Christian philosophy responding to the fall of Rome and exploring the tension between earthly power and eternal truth.",
		price: 1899,
		discountPercentage: 5,
		weight: 480,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 2–4 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/45304/pg45304.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/45304/pg45304.cover.medium.jpg",
		tags: ["philosophy", "religion", "theology", "classic"],
		era: "Ancient",
		genre: "Religious Philosophy",
		format: "Paperback",
		year: new Date("0426-01-01"),
		binding: "Softcover",
		categoryName: "Non-Fiction",
		conditionGrade: "B",
		authorName: "Saint Augustine",
		publisherName: "Oxford World's Classics",
	},
	{
		title: "Wuthering Heights",
		description:
			"A dark and turbulent novel of obsessive love, revenge, and generational trauma set on the Yorkshire moors.",
		price: 1499,
		discountPercentage: 12,
		weight: 360,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: ["https://www.gutenberg.org/cache/epub/768/pg768.cover.medium.jpg"],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/768/pg768.cover.medium.jpg",
		tags: ["gothic", "romance", "classic", "psychological"],
		era: "19th Century",
		genre: "Gothic Romance",
		format: "Paperback",
		year: new Date("1847-12-01"),
		binding: "Softcover",
		categoryName: "Romance",
		conditionGrade: "A",
		authorName: "Emily Brontë",
		publisherName: "Vintage Classics",
	},
	{
		title: "Moby Dick; Or, The Whale",
		description:
			"Ishmael joins Captain Ahab aboard the Pequod and witnesses a relentless, symbolic hunt for the white whale Moby Dick.",
		price: 1699,
		discountPercentage: 8,
		weight: 620,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 2–4 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/2701/pg2701.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/2701/pg2701.cover.medium.jpg",
		tags: ["adventure", "sea", "classic", "american literature"],
		era: "19th Century",
		genre: "Adventure Classic",
		format: "Hardcover",
		year: new Date("1851-10-18"),
		binding: "Hardcover",
		categoryName: "Fiction",
		conditionGrade: "B",
		authorName: "Herman Melville",
		publisherName: "Everyman's Library",
	},
	{
		title: "Pride and Prejudice",
		description:
			"Elizabeth Bennet navigates social expectation, family pressure, and changing first impressions in Austen’s enduring novel of wit and romance.",
		price: 1199,
		discountPercentage: 15,
		weight: 340,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/1342/pg1342.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/1342/pg1342.cover.medium.jpg",
		tags: ["romance", "classic", "british literature", "regency"],
		era: "19th Century",
		genre: "Classic Romance",
		format: "Paperback",
		year: new Date("1813-01-28"),
		binding: "Softcover",
		categoryName: "Romance",
		conditionGrade: "A+",
		authorName: "Jane Austen",
		publisherName: "Penguin Classics",
	},
	{
		title: "Romeo and Juliet",
		description:
			"Shakespeare’s tragic drama of two young lovers whose fate is sealed by family hatred and fatal misunderstanding.",
		price: 999,
		discountPercentage: 10,
		weight: 220,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/1513/pg1513.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/1513/pg1513.cover.medium.jpg",
		tags: ["drama", "tragedy", "classic", "romance"],
		era: "16th Century",
		genre: "Tragic Drama",
		format: "Paperback",
		year: new Date("1597-01-01"),
		binding: "Softcover",
		categoryName: "Drama",
		conditionGrade: "A",
		authorName: "William Shakespeare",
		publisherName: "Oxford World's Classics",
	},
	{
		title: "The Complete Works of William Shakespeare",
		description:
			"A comprehensive collection of Shakespeare’s plays and poems, spanning tragedies, comedies, histories, and sonnets.",
		price: 2999,
		discountPercentage: 7,
		weight: 1250,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 2–5 business days.",
		availabilityStatus: "In Stock",
		images: ["https://www.gutenberg.org/cache/epub/100/pg100.cover.medium.jpg"],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/100/pg100.cover.medium.jpg",
		tags: ["collected works", "drama", "poetry", "classic"],
		era: "16th–17th Century",
		genre: "Collected Drama & Poetry",
		format: "Hardcover",
		year: new Date("1623-01-01"),
		binding: "Hardcover",
		categoryName: "Drama",
		conditionGrade: "B",
		authorName: "William Shakespeare",
		publisherName: "Everyman's Library",
	},
	{
		title: "A Room with a View",
		description:
			"Lucy Honeychurch must choose between convention and genuine feeling in this elegant Edwardian coming-of-age romance.",
		price: 1249,
		discountPercentage: 10,
		weight: 290,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/2641/pg2641.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/2641/pg2641.cover.medium.jpg",
		tags: ["romance", "edwardian", "classic", "coming of age"],
		era: "20th Century",
		genre: "Romantic Literary Fiction",
		format: "Paperback",
		year: new Date("1908-01-01"),
		binding: "Softcover",
		categoryName: "Romance",
		conditionGrade: "A",
		authorName: "E. M. Forster",
		publisherName: "Vintage Classics",
	},
	{
		title: "Alice's Adventures in Wonderland",
		description:
			"Alice falls down a rabbit hole into a fantastical world of talking animals, riddles, and delightful nonsense.",
		price: 1099,
		discountPercentage: 5,
		weight: 240,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: ["https://www.gutenberg.org/cache/epub/11/pg11.cover.medium.jpg"],
		thumbnail: "https://www.gutenberg.org/cache/epub/11/pg11.cover.medium.jpg",
		tags: ["children", "fantasy", "classic", "nonsense literature"],
		era: "19th Century",
		genre: "Children's Fantasy",
		format: "Paperback",
		year: new Date("1865-11-26"),
		binding: "Softcover",
		categoryName: "Children & Young Adult",
		conditionGrade: "A+",
		authorName: "Lewis Carroll",
		publisherName: "Wordsworth Editions",
	},
	{
		title: "The Strange Case of Dr. Jekyll and Mr. Hyde",
		description:
			"A lawyer investigates the connection between respectable Dr. Jekyll and the violent Edward Hyde in this classic tale of dual identity.",
		price: 949,
		discountPercentage: 10,
		weight: 190,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: ["https://www.gutenberg.org/cache/epub/43/pg43.cover.medium.jpg"],
		thumbnail: "https://www.gutenberg.org/cache/epub/43/pg43.cover.medium.jpg",
		tags: ["gothic", "horror", "classic", "psychological"],
		era: "19th Century",
		genre: "Gothic Horror",
		format: "Paperback",
		year: new Date("1886-01-05"),
		binding: "Softcover",
		categoryName: "Mystery",
		conditionGrade: "A",
		authorName: "Robert Louis Stevenson",
		publisherName: "Penguin Classics",
	},
	{
		title: "Middlemarch",
		description:
			"A sweeping portrait of provincial life, ambition, marriage, and reform in one of the great achievements of English realism.",
		price: 1799,
		discountPercentage: 10,
		weight: 680,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 2–4 business days.",
		availabilityStatus: "In Stock",
		images: ["https://www.gutenberg.org/cache/epub/145/pg145.cover.medium.jpg"],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/145/pg145.cover.medium.jpg",
		tags: ["classic", "victorian", "literary fiction", "historical"],
		era: "19th Century",
		genre: "Literary Realism",
		format: "Hardcover",
		year: new Date("1871-12-01"),
		binding: "Hardcover",
		categoryName: "Historical Fiction",
		conditionGrade: "B",
		authorName: "George Eliot",
		publisherName: "Oxford World's Classics",
	},
	{
		title: "The Great Gatsby",
		description:
			"Nick Carraway becomes fascinated by the enigmatic Jay Gatsby and the glittering, hollow promise of the American Dream.",
		price: 1299,
		discountPercentage: 10,
		weight: 270,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/64317/pg64317.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/64317/pg64317.cover.medium.jpg",
		tags: ["american literature", "jazz age", "classic", "literary fiction"],
		era: "20th Century",
		genre: "Literary Fiction",
		format: "Paperback",
		year: new Date("1925-04-10"),
		binding: "Softcover",
		categoryName: "Fiction",
		conditionGrade: "A",
		authorName: "F. Scott Fitzgerald",
		publisherName: "Vintage Classics",
	},
	{
		title: "Jane Eyre: An Autobiography",
		description:
			"Jane Eyre’s journey from hardship to independence unfolds through love, secrecy, and fierce moral conviction.",
		price: 1349,
		discountPercentage: 15,
		weight: 390,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/1260/pg1260.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/1260/pg1260.cover.medium.jpg",
		tags: ["romance", "gothic", "classic", "bildungsroman"],
		era: "19th Century",
		genre: "Gothic Romance",
		format: "Paperback",
		year: new Date("1847-10-16"),
		binding: "Softcover",
		categoryName: "Romance",
		conditionGrade: "A",
		authorName: "Charlotte Brontë",
		publisherName: "Penguin Classics",
	},
	{
		title: "The Blue Castle: a novel",
		description:
			"Valancy Stirling breaks free from family expectations and discovers unexpected freedom, courage, and love.",
		price: 1149,
		discountPercentage: 10,
		weight: 310,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/67979/pg67979.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/67979/pg67979.cover.medium.jpg",
		tags: ["romance", "canadian literature", "classic", "women's fiction"],
		era: "20th Century",
		genre: "Romantic Fiction",
		format: "Paperback",
		year: new Date("1926-01-01"),
		binding: "Softcover",
		categoryName: "Romance",
		conditionGrade: "A+",
		authorName: "L. M. Montgomery",
		publisherName: "Wordsworth Editions",
	},
	{
		title: "Crime and Punishment",
		description:
			"Raskolnikov commits a murder he thinks he can justify, then spirals into guilt, paranoia, and moral crisis.",
		price: 1599,
		discountPercentage: 10,
		weight: 580,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 2–4 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/2554/pg2554.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/2554/pg2554.cover.medium.jpg",
		tags: ["russian literature", "psychological", "classic", "crime"],
		era: "19th Century",
		genre: "Psychological Crime Fiction",
		format: "Paperback",
		year: new Date("1866-01-01"),
		binding: "Softcover",
		categoryName: "Mystery",
		conditionGrade: "B",
		authorName: "Fyodor Dostoevsky",
		publisherName: "Oxford World's Classics",
	},
	{
		title: "Little Women; Or, Meg, Jo, Beth, and Amy",
		description:
			"The March sisters grow from girlhood into adulthood in this beloved novel of family, work, sacrifice, and affection.",
		price: 1299,
		discountPercentage: 12,
		weight: 420,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/37106/pg37106.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/37106/pg37106.cover.medium.jpg",
		tags: ["classic", "family", "coming of age", "children & young adult"],
		era: "19th Century",
		genre: "Coming-of-Age Fiction",
		format: "Paperback",
		year: new Date("1868-01-01"),
		binding: "Softcover",
		categoryName: "Children & Young Adult",
		conditionGrade: "A",
		authorName: "Louisa May Alcott",
		publisherName: "Penguin Classics",
	},
	{
		title: "The Enchanted April",
		description:
			"Four women leave England for an Italian castle, where beauty, distance, and friendship begin to transform their lives.",
		price: 1199,
		discountPercentage: 8,
		weight: 280,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/16389/pg16389.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/16389/pg16389.cover.medium.jpg",
		tags: ["classic", "friendship", "italy", "women's fiction"],
		era: "20th Century",
		genre: "Literary Fiction",
		format: "Paperback",
		year: new Date("1922-01-01"),
		binding: "Softcover",
		categoryName: "Fiction",
		conditionGrade: "A",
		authorName: "Elizabeth von Arnim",
		publisherName: "Vintage Classics",
	},
	{
		title: "The Picture of Dorian Gray",
		description:
			"A beautiful young man remains outwardly youthful while his portrait bears the marks of corruption and sin.",
		price: 1099,
		discountPercentage: 10,
		weight: 260,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: ["https://www.gutenberg.org/cache/epub/174/pg174.cover.medium.jpg"],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/174/pg174.cover.medium.jpg",
		tags: ["gothic", "philosophical", "classic", "horror"],
		era: "19th Century",
		genre: "Philosophical Gothic Fiction",
		format: "Paperback",
		year: new Date("1890-06-20"),
		binding: "Softcover",
		categoryName: "Fiction",
		conditionGrade: "A",
		authorName: "Oscar Wilde",
		publisherName: "Wordsworth Editions",
	},
	{
		title: "Dracula",
		description:
			"Through diaries, letters, and reports, a small group confronts Count Dracula as he spreads terror from Transylvania to England.",
		price: 1399,
		discountPercentage: 10,
		weight: 410,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: ["https://www.gutenberg.org/cache/epub/345/pg345.cover.medium.jpg"],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/345/pg345.cover.medium.jpg",
		tags: ["gothic", "vampire", "classic", "horror"],
		era: "19th Century",
		genre: "Gothic Horror",
		format: "Paperback",
		year: new Date("1897-05-26"),
		binding: "Softcover",
		categoryName: "Fantasy",
		conditionGrade: "A",
		authorName: "Bram Stoker",
		publisherName: "Penguin Classics",
	},
	{
		title: "Beowulf: An Anglo-Saxon Epic Poem",
		description:
			"A classic heroic poem in translation, telling of Beowulf’s battles against Grendel, Grendel’s mother, and a dragon.",
		price: 1249,
		discountPercentage: 5,
		weight: 250,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/16328/pg16328.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/16328/pg16328.cover.medium.jpg",
		tags: ["poetry", "epic", "mythology", "classic"],
		era: "Medieval",
		genre: "Epic Poetry",
		format: "Paperback",
		year: new Date("1892-01-01"),
		binding: "Softcover",
		categoryName: "Poetry",
		conditionGrade: "B",
		authorName: "J. Lesslie Hall",
		publisherName: "Oxford World's Classics",
	},
	{
		title: "A Modest Proposal",
		description:
			"Jonathan Swift’s savage satirical essay exposes cruelty, indifference, and political hypocrisy through a deliberately shocking argument.",
		price: 799,
		discountPercentage: 0,
		weight: 120,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/1080/pg1080.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/1080/pg1080.cover.medium.jpg",
		tags: ["satire", "essay", "classic", "political"],
		era: "18th Century",
		genre: "Satirical Essay",
		format: "Paperback",
		year: new Date("1729-01-01"),
		binding: "Softcover",
		categoryName: "Non-Fiction",
		conditionGrade: "A",
		authorName: "Jonathan Swift",
		publisherName: "Wordsworth Editions",
	},
	{
		title: "A Doll's House : a play",
		description:
			"Henrik Ibsen’s influential drama follows Nora Helmer as she confronts the limits of marriage, respectability, and selfhood.",
		price: 899,
		discountPercentage: 10,
		weight: 180,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: [
			"https://www.gutenberg.org/cache/epub/2542/pg2542.cover.medium.jpg",
		],
		thumbnail:
			"https://www.gutenberg.org/cache/epub/2542/pg2542.cover.medium.jpg",
		tags: ["drama", "classic", "feminism", "theatre"],
		era: "19th Century",
		genre: "Modern Drama",
		format: "Paperback",
		year: new Date("1879-01-01"),
		binding: "Softcover",
		categoryName: "Drama",
		conditionGrade: "A",
		authorName: "Henrik Ibsen",
		publisherName: "Penguin Classics",
	},
	{
		title: "Adventures of Huckleberry Finn",
		description:
			"Huck Finn and Jim journey down the Mississippi in a novel that combines adventure, humor, and biting social criticism.",
		price: 1199,
		discountPercentage: 10,
		weight: 330,
		warrantyInformation: "No warranty for used books.",
		shippingInformation: "Ships in 1–3 business days.",
		availabilityStatus: "In Stock",
		images: ["https://www.gutenberg.org/cache/epub/76/pg76.cover.medium.jpg"],
		thumbnail: "https://www.gutenberg.org/cache/epub/76/pg76.cover.medium.jpg",
		tags: ["adventure", "american literature", "classic", "coming of age"],
		era: "19th Century",
		genre: "Adventure Fiction",
		format: "Paperback",
		year: new Date("1884-12-10"),
		binding: "Softcover",
		categoryName: "Fiction",
		conditionGrade: "B",
		authorName: "Mark Twain",
		publisherName: "Vintage Classics",
	},
] as const;
